### ISSUE TITLE
Hail Aus Model Compatibility with latest OASIS Platform

### ISSUE THREAD

**Issue by kprasadpn** [risk-frontiers/OasisIntegration#10]
Hi, 
 
We have faced some issues with model execution run and forced to upgrade the platform to latest version now we are trying to integrate risk-frontier (OasisLMF Complex Model Integration of HailAUS 7) with oasis latest version as below :   

API :1.9.0
UI  : 1.8.0

Do we need to stick on any specific platform version ?
It will be great if you can share this details . 

Oasis platform source 
https://github.com/OasisLMF/OasisPlatform/tree/1.9.0

**Comment by rtahiry** [comment]
Support for API 1.9.0 and UI 1.8.0 has just been released.
